CUDA_VISIBLE_DEVICES=0 python unlearn_train_cogvideox_transformer.py \
  --is_train False \
  --prompt="A man standing behind the camera, looking at the viewer" \
  --output_dir="/root/autodl-tmp/output" \
  --model_path /root/autodl-tmp/models/cogvideox-2b \
  --num_inference_steps 50 \
  --num_frames 49 \
  --num_epoch 2 \
  --generate_type t2v \
  --dtype float16 \
  --seed 42